### ISSUE TITLE
Include OpenBlasMultiThread

### ISSUE THREAD

**Issue by rolfjl** [Python-Ensemble-Toolbox/PET#48]
It seems to be something seriously wrong when running flow with mpirun. May be related to the fact that OpenBlasMultiThread is not included from the "old pipt" version.

**Comment by KriFos1** [comment]
All function calls are currently performed by p_map in the p_tqdm package. p_tqdm is a wrapper around pathos.multiprocessing and tqdm. According to the [documentation,](https://github.com/uqfoundation/pathos/blob/master/pathos/multiprocessing.py) this "leverages the python's multiprocessing module, and thus has many of the limitations associated with that module."

What errors are you observing?

**Comment by rolfjl** [comment]
Issue fixed according to : https://github.com/OPM/opm-simulators/issues/3825
